export { default as HomePageComponent } from "./home-page-component/home-page-component"
export { default as CoursesPageComponent } from "./courses-page-component/courses-page-component"
export { default as BooksPageComponent } from "./books-page-component/books-page-component"
export { default as ArticlesPageComponent } from "./articles-page-component/articles-page-component"
export { default as ArticleDetailedPageComponent } from "./articles-page-component/article-detailed-page-component"
export { default as AboutPageComponent } from "./about-page-component/about-page-component"
export { default as ContactPageComponet } from "./contact-page-componet/contact-page-componet"
export { default as PricingPageComponent } from "./pricing-page-component/pricing-page-component"
export { default as FaqPageComponent } from "./faq-page-component/faq-page-component"
export { default as AuthPageComponet } from "./auth-page-componet/auth-page-componet"

